%% BEM SIMULATION
%Parameters derived from the "DTU 10 MW reference wind turbine"

%%
close all
clear
clc

%% GENERAL DATA
R = 89.17;          % [m] : Rotor radius
B = 3;              % [-] : Number of blades
Prated = 10e6;      % [W] : Rated poxer
Vmin = 4;           % [m/s] : Cut-in wind speed
Vmax = 25;          % [m/s] : Cut out wind speed
Vrated = 11.4;      % [m/s] : Rated wind speed (the wind speed at which the rated power (the maximum output power) of the electrical generator is reached)
rho = 1.225;        % [kg/s] : Air density
n_airfoil = 5;      % [-] : Number of sections available

%% Airfoil section data

% Blade table is in file bladedat.txt 
T = load('bladedat.txt');
filename = 'NREL LARGE BLADES'

r_list = T(:,1);                   % [m] : Radius vector
Beta_list = pi/180*T(:,2);         % [rad] : Local twist angle vector
c_list = (T(:,3));                   % [m] : Chord vector
Thick_list = T(:,4);               % [%] : Thickness vector

% cylinder.txt and FFA-W3-xxx.txt are airfoil sections (xxx thickness)
Xcylinder = load('cylinder.txt');
S810 = load('NRELS810.txt');
S809 = load('NRELS809.txt');
S814 = load('NRELS814.txt');
S815 = load('NRELS815.txt');

aoa_list = pi/180*[S810(:,1) S809(:,1) S814(:,1) S815(:,1) Xcylinder(:,1)];   % [rad] Vector of angle of attack for each section
Cl_list = [S810(:,2) S809(:,2) S814(:,2) S815(:,2) Xcylinder(:,2)];           % [-] Vector of lift coefficients for each section
Cd_list = [S810(:,3) S809(:,3) S814(:,3) S815(:,3) Xcylinder(:,3)];           % [-] Vector of drag coefficients for each section
Cm_list = [S810(:,5) S809(:,5) S814(:,5) S815(:,4) Xcylinder(:,4)];           % [-] Vector of torque coefficients for each section
Thick_prof_list = [18.0; 21.0; 24.9; 26.0; 100.0];                                % [%] Vector of thicknesses that have available data


%% CP and CT matrix calculations
V0 = Vrated;              % [m/s] : Wind speed (it is set to rated wind speed to reach the maximum value for CP)
Re = V0*2*R/(1.5E+5);     % [-] : Reynold's on the scale of the wind turbine

% Initialization of coordinate matrices for CP and CT
Theta_p_list = [-0.04:0.01:0.09];                             % [rad] : Global pitch angle list(to optimise)        
Lambda_list =  [4:0.2:13];                                      % [-] : Tip speed ratio list (to optimise)
CP_matrix = zeros(length(Lambda_list),length(Theta_p_list));   % [-] : Matrix of CP(lambda, theta_p)
CT_matrix = zeros(length(Lambda_list),length(Theta_p_list));   % [-] : Matrix of CT(lambda, theta_p)

% Initialization of local load list (we keep only pn and pt values for r < 0.985*R)
pn_list = zeros(length(r_list)-length(find(r_list >= 0.985*R))+1,1);   % [N/m] : Normal effort storage vector 
pt_list = zeros(length(r_list)-length(find(r_list >= 0.985*R))+1,1);   % [N/m] : Tangential effort storage vector 

% Add to the lists the values pn = 0N/m and pt = 0N/m for r = R
r_list_bis = [r_list(1:length(r_list)-length(find(r_list >= 0.985*R)));R]; % [m] : Radius vector (r values for r < 0.985*R and r=R)

figure
hold on
ylim([0 0.5])

for i=1:length(Lambda_list)
    lambda = Lambda_list(i);          %  [-] : Tip speed ratio n°i to test
    
    for j=1:length(Theta_p_list)
        theta_p = Theta_p_list(j);    %  [rad] : Global pitch angle n°j to test
        
        for i_radius=1:(length(r_list)-length(find(r_list >= 0.985*R))) % We only keep values for r < 0.985*R)
            
            % Initialisations
            r = r_list(i_radius,1);          % [m] : Radial position n°i_radius
            c = c_list(i_radius,1);          % [m] : Chord for radial position n°i_radius
            beta = Beta_list(i_radius,1);    % [rad] : Local twist for radial position n°i_radius
            k = Thick_list(i_radius,1);      % [rad] : Thichness of the 2D profile for radial position n°i_radius
            
            % Calculate pn and pt for one radial position r
            [pn_r, pt_r, alpha_max] = BEM_Algorithm2D(V0, R, B, rho, n_airfoil, lambda, theta_p, r, c, beta, k, aoa_list, Cl_list, Cd_list, Thick_prof_list, i_radius);
            pn_list(i_radius,1) = pn_r; 
            pt_list(i_radius,1) = pt_r;
           
        end
           
        % Calculation of integral to get Thrust and Power
        disp(pn_list)

        T = B * trapz(r_list_bis(4:end), pn_list(4:end));                             %[N] : Thrust force for the entire wind turbine T(lambda(i),theta_p(j))
        P = lambda*V0/R * B * trapz(r_list_bis(4:end),r_list_bis(4:end).*pt_list(4:end));    %[W] : Power generated by torque for the entire wind turbine P(lambda(i),theta_p(j)) = w*M_R (torque moment)
        
        % Calculation of CT and CP
        CT = T / (0.5*rho*pi*R^2*V0^2);    %[-] : Thrust coefficient
        CP = P / (0.5*rho*pi*R^2*V0^3);    %[-] : Power coefficient
        
        % Update of CP and CT matrices
        CT_matrix(i,j) = CT;
        CP_matrix(i,j) = CP;
    end
end

%% CP_opt, CP and CT contour plot

% Calculate Cp_opt(lambda_opt, theta_p_opt)
CP_opt = max(max(CP_matrix))                                  % [-] Optimal power coefficient
[i_lambda_opt,j_theta_p_opt]=find(CP_matrix==CP_opt);
lambda_opt = Lambda_list(i_lambda_opt);                         % [-] Optimal TSR
theta_p_opt = 180/pi*Theta_p_list(j_theta_p_opt);               % [°] Optimal pitch angle)

disp('C_(P,opt) [-]')
disp(CP_opt);
disp('\lambda_(opt) [-]')
disp(lambda_opt);
disp('\theta_(p,opt) [°]')
disp(theta_p_opt);

% CP contour plot

figure;
clear xlim
clear ylim
hold on
contour(Lambda_list,180/pi*Theta_p_list,CP_matrix.',[0:0.02:1],'ShowText','on')
x_min_graph = xlim;
y_min_graph = ylim;
x_min_graph = x_min_graph(1);
y_min_graph = y_min_graph(1);
plot([lambda_opt lambda_opt], [y_min_graph CP_opt], 'k:')
plot([x_min_graph lambda_opt], [CP_opt CP_opt], 'k:')
plot(lambda_opt, CP_opt, 'bx')
colorbar;
title(append('Power coefficient C_P(\lambda, \theta_p) for ',filename));
xlabel('TSR : \lambda [-]');
ylabel('Pitch angle : \theta_p [°]');

% CT contour plot
figure;
contour(Lambda_list,180/pi*Theta_p_list,CT_matrix.',[0:0.1:1.5],'ShowText','on')
colorbar;
title(append('Thrust coefficient C_T(\lambda, \theta_p) for '),filename);
xlabel('TSR : \lambda [-]');
ylabel('Pitch angle : \theta_p [°]');

